// src/lib/gallery-images-v2.ts
// 83 imágenes SEO de la segunda galería de Samsara Tattoo Studio.
// Cada nombre contiene keywords + comuna + marca para SEO local.

export interface GalleryImage {
  src: string;
  alt: string;
  category: "tatuaje" | "pintura" | "aerografia";
  comuna?: string;
}

const BASE = "/images/samarasegundaGaleria";

export const GALLERY_IMAGES_V2: GalleryImage[] = [
  { src: `${BASE}/realismo-sombras-retratos-providencia-samsara-tattoo.jpeg`, alt: "Realismo sombras retratos en Providencia - Samsara Tattoo Studio", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/samsara-tattoo-cover-arreglo-tinta-santiago.jpeg`, alt: "Cover y arreglo de tinta en Santiago - Samsara Tattoo", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/linea-fina-minimalista-flores-lascondes-samsara-tattoo.jpeg`, alt: "Línea fina minimalista flores en Las Condes - Samsara Tattoo", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/estudio-tatuajes-manga-completa-nunoa-samsara.jpeg`, alt: "Manga completa tatuaje en Ñuñoa - Samsara Tattoo Studio", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/samsara-tattoo-studio-lettering-caligrafia-frases-vitacura.jpeg`, alt: "Lettering caligrafía frases en Vitacura - Samsara Tattoo", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/cover-up-tatuajes-animales-lareina-samsara.jpeg`, alt: "Cover up de animales en La Reina - Samsara Tattoo", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/tatuajes-hombres-cuello-hombres-lobarnechea-samsara-tattoo.jpeg`, alt: "Tatuajes en cuello para hombres en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/parejas-diseno-exclusivo-macul-samsara-tattoo.jpeg`, alt: "Diseño exclusivo para parejas en Macul - Samsara Tattoo", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/samsara-tattoo-microrealismo-detalles-piel-sanmiguel.jpeg`, alt: "Micro realismo detalles en piel en San Miguel - Samsara", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/profesional-bioseguridad-estudio-privado-providencia-samsara-tattoo.jpeg`, alt: "Bioseguridad estudio privado en Providencia - Samsara Tattoo", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/estudio-tatuajes-antebrazo-realismo-santiago-samsara.jpeg`, alt: "Antebrazo realismo en Santiago - Samsara Tattoo Studio", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/samsara-tattoo-studio-minimalista-trazos-delicado-lascondes.jpeg`, alt: "Minimalista trazos delicados en Las Condes - Samsara", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/cover-up-tatuajes-letras-nunoa-samsara.jpeg`, alt: "Cover up de letras en Ñuñoa - Samsara Tattoo", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/tatuajes-hombres-leones-tigres-vitacura-samsara-tattoo.jpeg`, alt: "Leones y tigres en Vitacura - Samsara Tattoo Studio", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/reparacion-cover-tapado-lareina-samsara-tattoo.jpeg`, alt: "Reparación cover tapado en La Reina - Samsara Tattoo", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/samsara-tattoo-realismo-sombras-retratos-lobarnechea.jpeg`, alt: "Realismo sombras retratos en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/cover-arreglo-tinta-negra-macul-samsara-tattoo.jpeg`, alt: "Arreglo de tinta negra en Macul - Samsara Tattoo", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/estudio-tatuajes-linea-fina-sanmiguel-samsara.jpeg`, alt: "Línea fina en San Miguel - Samsara Tattoo Studio", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/samsara-tattoo-studio-manga-completa-brazo-providencia.jpeg`, alt: "Manga completa brazo en Providencia - Samsara Tattoo", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/cover-up-tatuajes-lettering-santiago-samsara.jpeg`, alt: "Cover up lettering en Santiago - Samsara Tattoo", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/tatuajes-hombres-animales-fauna-lascondes-samsara-tattoo.jpeg`, alt: "Animales y fauna en Las Condes - Samsara Tattoo", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/cuello-hombres-sombras-nunoa-samsara-tattoo.jpeg`, alt: "Cuello con sombras en Ñuñoa - Samsara Tattoo", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/samsara-tattoo-parejas-diseno-exclusivo-vitacura.jpeg`, alt: "Parejas diseño exclusivo en Vitacura - Samsara", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/microrealismo-detalles-piel-retratos-lareina-samsara-tattoo.jpeg`, alt: "Micro realismo detalles en La Reina - Samsara", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/estudio-tatuajes-profesional-bioseguridad-lobarnechea-samsara.jpeg`, alt: "Bioseguridad profesional en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/samsara-tattoo-studio-antebrazo-realismo-sombras-macul.jpeg`, alt: "Antebrazo realismo sombras en Macul - Samsara", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/cover-up-tatuajes-minimalista-sanmiguel-samsara.jpeg`, alt: "Cover up minimalista en San Miguel - Samsara", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/tatuajes-hombres-letras-cursiva-providencia-samsara-tattoo.jpeg`, alt: "Letras cursiva en Providencia - Samsara Tattoo", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/leones-tigres-aves-santiago-samsara-tattoo.jpeg`, alt: "Leones tigres y aves en Santiago - Samsara Tattoo", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/samsara-tattoo-reparacion-cover-tapado-lascondes.jpeg`, alt: "Reparación cover tapado en Las Condes - Samsara", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/realismo-sombras-retratos-antebrazo-nunoa-samsara-tattoo.jpeg`, alt: "Realismo sombras antebrazo en Ñuñoa - Samsara", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/estudio-tatuajes-cover-arreglo-vitacura-samsara.jpeg`, alt: "Cover arreglo en Vitacura - Samsara Tattoo Studio", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/samsara-tattoo-studio-linea-fina-minimalista-lareina.jpeg`, alt: "Línea fina minimalista en La Reina - Samsara", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/cover-up-tatuajes-manga-lobarnechea-samsara.jpeg`, alt: "Cover up manga en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/tatuajes-hombres-lettering-caligrafia-macul-samsara-tattoo.jpeg`, alt: "Lettering caligrafía en Macul - Samsara Tattoo", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/animales-fauna-mascotas-sanmiguel-samsara-tattoo.jpeg`, alt: "Animales fauna mascotas en San Miguel - Samsara", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/samsara-tattoo-cuello-hombres-sombras-providencia.jpeg`, alt: "Cuello hombres sombras en Providencia - Samsara", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/parejas-diseno-exclusivo-tinta-santiago-samsara-tattoo.jpeg`, alt: "Parejas diseño exclusivo en Santiago - Samsara", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/estudio-tatuajes-microrealismo-detalles-lascondes-samsara.jpeg`, alt: "Micro realismo detalles en Las Condes - Samsara", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/samsara-tattoo-studio-profesional-bioseguridad-estudio-nunoa.jpeg`, alt: "Bioseguridad estudio en Ñuñoa - Samsara Tattoo", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/cover-up-tatuajes-antebrazo-vitacura-samsara.jpeg`, alt: "Cover up antebrazo en Vitacura - Samsara Tattoo", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/tatuajes-hombres-minimalista-trazos-lareina-samsara-tattoo.jpeg`, alt: "Minimalista trazos en La Reina - Samsara Tattoo", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/letras-cursiva-gotica-lobarnechea-samsara-tattoo.jpeg`, alt: "Letras cursiva gótica en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/samsara-tattoo-leones-tigres-aves-macul.jpeg`, alt: "Leones tigres aves en Macul - Samsara Tattoo", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/reparacion-cover-tapado-antiguo-sanmiguel-samsara-tattoo.jpeg`, alt: "Reparación cover tapado en San Miguel - Samsara", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/estudio-tatuajes-realismo-sombras-providencia-samsara.jpeg`, alt: "Realismo sombras en Providencia - Samsara Tattoo", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/samsara-tattoo-studio-cover-arreglo-tinta-santiago.jpeg`, alt: "Cover arreglo tinta en Santiago - Samsara Tattoo", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/cover-up-tatuajes-linea-lascondes-samsara.jpeg`, alt: "Cover up línea en Las Condes - Samsara Tattoo", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/tatuajes-hombres-manga-completa-nunoa-samsara-tattoo.jpeg`, alt: "Manga completa en Ñuñoa - Samsara Tattoo Studio", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/lettering-caligrafia-frases-vitacura-samsara-tattoo.jpeg`, alt: "Lettering caligrafía frases en Vitacura - Samsara", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/samsara-tattoo-animales-fauna-mascotas-lareina.jpeg`, alt: "Animales fauna en La Reina - Samsara Tattoo", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/cuello-hombres-sombras-arte-lobarnechea-samsara-tattoo.jpeg`, alt: "Cuello sombras arte en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/estudio-tatuajes-parejas-diseno-macul-samsara.jpeg`, alt: "Parejas diseño en Macul - Samsara Tattoo Studio", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/samsara-tattoo-studio-microrealismo-detalles-piel-sanmiguel.jpeg`, alt: "Micro realismo en San Miguel - Samsara Tattoo", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/cover-up-tatuajes-profesional-providencia-samsara.jpeg`, alt: "Cover profesional en Providencia - Samsara", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/tatuajes-hombres-antebrazo-realismo-santiago-samsara-tattoo.jpeg`, alt: "Antebrazo realismo en Santiago - Samsara Tattoo", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/minimalista-trazos-delicado-lascondes-samsara-tattoo.jpeg`, alt: "Minimalista trazos en Las Condes - Samsara Tattoo", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/samsara-tattoo-letras-cursiva-gotica-nunoa.jpeg`, alt: "Letras cursiva gótica en Ñuñoa - Samsara Tattoo", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/leones-tigres-aves-realismo-vitacura-samsara-tattoo.jpeg`, alt: "Leones tigres aves realismo en Vitacura - Samsara", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/estudio-tatuajes-reparacion-cover-lareina-samsara.jpeg`, alt: "Reparación cover en La Reina - Samsara Tattoo", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/samsara-tattoo-studio-realismo-sombras-retratos-lobarnechea.jpeg`, alt: "Realismo sombras retratos en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/cover-up-tatuajes-cover-macul-samsara.jpeg`, alt: "Cover up en Macul - Samsara Tattoo Studio", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/tatuajes-hombres-linea-fina-sanmiguel-samsara-tattoo.jpeg`, alt: "Línea fina en San Miguel - Samsara Tattoo", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/manga-completa-brazo-providencia-samsara-tattoo.jpeg`, alt: "Manga completa brazo en Providencia - Samsara", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/samsara-tattoo-lettering-caligrafia-frases-santiago.jpeg`, alt: "Lettering caligrafía frases en Santiago - Samsara", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/animales-fauna-mascotas-realismo-lascondes-samsara-tattoo.jpeg`, alt: "Animales fauna realismo en Las Condes - Samsara", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/estudio-tatuajes-cuello-hombres-nunoa-samsara.jpeg`, alt: "Cuello hombres en Ñuñoa - Samsara Tattoo Studio", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/samsara-tattoo-studio-parejas-diseno-exclusivo-vitacura.jpeg`, alt: "Parejas diseño exclusivo en Vitacura - Samsara", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/cover-up-tatuajes-microrealismo-lareina-samsara.jpeg`, alt: "Cover up micro realismo en La Reina - Samsara", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/tatuajes-hombres-profesional-bioseguridad-lobarnechea-samsara-tattoo.jpeg`, alt: "Bioseguridad profesional en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/antebrazo-realismo-sombras-macul-samsara-tattoo.jpeg`, alt: "Antebrazo realismo sombras en Macul - Samsara", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/samsara-tattoo-minimalista-trazos-delicado-sanmiguel.jpeg`, alt: "Minimalista trazos delicados en San Miguel - Samsara", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/letras-cursiva-gotica-nombres-providencia-samsara-tattoo.jpeg`, alt: "Letras cursiva gótica nombres en Providencia - Samsara", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/estudio-tatuajes-leones-tigres-santiago-samsara.jpeg`, alt: "Leones tigres en Santiago - Samsara Tattoo Studio", category: "tatuaje", comuna: "santiago" },
  { src: `${BASE}/samsara-tattoo-studio-reparacion-cover-tapado-lascondes.jpeg`, alt: "Reparación cover tapado en Las Condes - Samsara", category: "tatuaje", comuna: "las-condes" },
  { src: `${BASE}/cover-up-tatuajes-realismo-nunoa-samsara.jpeg`, alt: "Cover up realismo en Ñuñoa - Samsara Tattoo", category: "tatuaje", comuna: "nunoa" },
  { src: `${BASE}/tatuajes-hombres-cover-arreglo-vitacura-samsara-tattoo.jpeg`, alt: "Cover arreglo en Vitacura - Samsara Tattoo", category: "tatuaje", comuna: "vitacura" },
  { src: `${BASE}/linea-fina-minimalista-lareina-samsara-tattoo.jpeg`, alt: "Línea fina minimalista en La Reina - Samsara", category: "tatuaje", comuna: "la-reina" },
  { src: `${BASE}/samsara-tattoo-manga-completa-brazo-lobarnechea.jpeg`, alt: "Manga completa brazo en Lo Barnechea - Samsara", category: "tatuaje", comuna: "lo-barnechea" },
  { src: `${BASE}/lettering-caligrafia-frases-diseno-macul-samsara-tattoo.jpeg`, alt: "Lettering caligrafía frases en Macul - Samsara", category: "tatuaje", comuna: "macul" },
  { src: `${BASE}/estudio-tatuajes-animales-fauna-sanmiguel-samsara.jpeg`, alt: "Animales fauna en San Miguel - Samsara Tattoo", category: "tatuaje", comuna: "san-miguel" },
  { src: `${BASE}/samsara-tattoo-studio-cuello-hombres-sombras-providencia.jpeg`, alt: "Cuello hombres sombras en Providencia - Samsara", category: "tatuaje", comuna: "providencia" },
  { src: `${BASE}/parejas-diseno-exclusivo-santiago-samsara-tattoo.jpeg`, alt: "Parejas diseño exclusivo en Santiago - Samsara", category: "tatuaje", comuna: "santiago" },
];
